name: selectable_items
description: Selectable Items Parameter~
version: 1.0.2
homepage: https://github.com/wxxedu/selectable_items
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3

#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  lints: ^2.0.0
  test: ^1.16.0
